name: Run Playwright API Call

on:
  workflow_dispatch:   # Trigger manually

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call Playwright Run API
        run: |
          curl --location 'https://d7c538db30d1.ngrok-free.app/api/v1/playwright/run-tests-ciCD?id=281,282&email=finalPlanCheck@yopmail.com'
