name: Run Playwright API Call

on:
  workflow_dispatch:   # Trigger manually

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call Playwright Run API
        run: |
          curl --location 'https://e306aaaacf16.ngrok-free.app/api/v1/playwright/run-tests-ciCD?id=304,305&projectId=74&email=finalPlanCheck@yopmail.com'
